### ISSUE TITLE
安装 Java SDK 1.8 - Spring Dev

### ISSUE THREAD

**Issue by rainboyan** [springdev-io/springdev-issues#1]
http://springdev.io/blog/2018/jdk.html 

 Spring Dev Site

**Comment by rainboyan** [comment]
SpringDev.IO是专门为广大Spring开发者们提供的一个在线技术资讯、博客文章、培训教程的网站，我们将提供原创的技术教程，国内外技术资讯、新闻报导、新书发布、视频讲座等内丰富内容，欢迎浏览查看和在此讨论。

**Comment by rainboyan** [comment]
网站速度经过优化已经比较快了，并且支持HTTPS。

**Comment by rainboyan** [comment]
示例代码需要精简和增加一些说明

**Comment by liupeng613** [comment]
之前居然一直没发现评论。。。支持下

**Comment by iriwen** [comment]
linux上面的安装教程没有说明下
